language: node_js

sudo: false

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

node_js:
  - "stable"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

notifications:
  email:
    - oferhe@gmail.com
